### ISSUE TITLE
Implementation problems

### ISSUE THREAD

**Issue by mittalrajat** [yuxng/PoseCNN#1]
Hi Yu Xiang,

Thanks for providing the code for your paper. I have been having some problems downloading and running the commands that you provided.

1. When I run the demo file, I get the error "nError: Path does not exist: /home/rajatmittal/Documents/posecnn/tools/../lib/datasets/../../data/LOV/models/002_master_chef_can/points.xyz". Do you know why this is happening?
2. Your YCB dataset is huge. 265GB. Is it possible for you to provide a trimmed down version for it.
3. You mention in step 4 that it is optional. Do I still have to compile the cython interface that you mention in step 4?
4. The number of dependencies for lib/synthesize are huge. Again, do I have to install it.

Your help would be really appreciated.

Thanks.

**Comment by yuxng** [comment]
1. These are model points included in the YCB_Video dataset. I have added these files to the repo. You can do git pull to get them.
2. I need to see how to trim.
3. Yes, the cython includes some other packages needed
4. If you do not install it, you need to comment out several lines in the code that load the synthesize library

**Comment by mittalrajat** [comment]
Hi Yu Xiang,

Thanks for your reply and for answering my queries. As I was trying to run the demo version, I get this error.

Traceback (most recent call last):
  File "./tools/test_net.py", line 103, in <module>
    from networks.factory import get_network
  File "/home/rajatmittal/Documents/posecnn/tools/../lib/networks/__init__.py", line 8, in <module>
    from .vgg16 import vgg16
  File "/home/rajatmittal/Documents/posecnn/tools/../lib/networks/vgg16.py", line 2, in <module>
    from networks.network import Network
  File "/home/rajatmittal/Documents/posecnn/tools/../lib/networks/network.py", line 6, in <module>
    import backprojecting_layer.backprojecting_op as backproject_op
  File "/home/rajatmittal/Documents/posecnn/tools/../lib/backprojecting_layer/backprojecting_op.py", line 5, in <module>
    _backprojecting_module = tf.load_op_library(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/rajatmittal/Documents/posecnn/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3_

I have been trying to search online but haven't really found any solutions. Do you know what might be the issue. I will keep searching.

Thanks.

**Comment by yuxng** [comment]
The error may because the flag -D_GLIBCXX_USE_CXX11_ABI=0 in compiling the new layers.
If your tensorflow is compiled with -D_GLIBCXX_USE_CXX11_ABI=0, you need to add -D_GLIBCXX_USE_CXX11_ABI=0 to the make.sh file to compile. I think for pre-built tensorflow, you need to add this flag.

**Comment by doublechenchen** [comment]
I added this before, i still error
'nvcc -std=c++11 -c -o average_distance_loss_op_gpu.cu.o average_distance_loss_op_gpu.cu.cc \
	-I $TF_INC -I$TF_INC/external/nsync/public -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_50

g++ -std=c++11 -shared -o average_distance_loss.so average_distance_loss_op.cc \
	average_distance_loss_op_gpu.cu.o -I $TF_INC -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -I$TF_INC/external/nsync/public -fPIC -lcudart -L$CUDA_PATH/lib64 -L$TF_LIB -ltensorflow_framework '

should i add like this?

**Comment by nkalavak** [comment]
running :~/Downloads/PoseCNN-master$ ./experiments/scripts/demo.sh $GPU_ID
I get
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/002_master_chef_can/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/003_cracker_box/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/004_sugar_box/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/005_tomato_soup_can/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/006_mustard_bottle/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/007_tuna_fish_can/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/008_pudding_box/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/009_gelatin_box/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/010_potted_meat_can/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/011_banana/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/019_pitcher_base/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/021_bleach_cleanser/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/024_bowl/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/025_mug/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/035_power_drill/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/036_wood_block/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/037_scissors/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/040_large_marker/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/051_large_clamp/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/052_extra_large_clamp/points.xyz
/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/datasets/../../data/LOV/models/061_foam_brick/points.xyz
data/demo_images/000001-color.png
data/demo_images/000001-depth.png
data/demo_images/000002-color.png
data/demo_images/000002-depth.png
data/demo_images/000003-color.png
data/demo_images/000003-depth.png
data/demo_images/000004-color.png
data/demo_images/000004-depth.png
data/demo_images/000005-color.png
data/demo_images/000005-depth.png
{'intrinsic_matrix': array([[1.066778e+03, 0.000000e+00, 3.129869e+02],
       [0.000000e+00, 1.067487e+03, 2.413109e+02],
       [0.000000e+00, 0.000000e+00, 1.000000e+00]]), 'factor_depth': 10000.0}
/gpu:0
Traceback (most recent call last):
  File "./tools/demo.py", line 118, in <module>
    from networks.factory import get_network
  File "/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/networks/__init__.py", line 8, in <module>
    from .vgg16 import vgg16
  File "/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/networks/vgg16.py", line 2, in <module>
    from networks.network import Network
  File "/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/networks/network.py", line 6, in <module>
    import backprojecting_layer.backprojecting_op as backproject_op
  File "/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/backprojecting_layer/backprojecting_op.py", line 5, in <module>
    _backprojecting_module = tf.load_op_library(filename)
  File "/home/nivedithak/tensorflow2/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/nivedithak/Downloads/PoseCNN-master/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3_

**Comment by Kaju-Bubanja** [comment]
I get the same error as above, any idea what tf version we should use?

**Comment by iretiayo** [comment]
Any idea what the fix for this is?

**Comment by Kaju-Bubanja** [comment]
@iretiayo I made an issue how to build this? There is a fork with detailed instruction that should help you to get this project running

**Comment by hangwudy** [comment]
@nkalavak I have the exact same problem, do you have fixed it?

**Comment by iris0329** [comment]
@Kaju-Bubanja Kaju-Bubanja, thank u so much, i am not trying your version, but really really happy to find this !!!
