### ISSUE TITLE
KeyError: 'unknown network: vgg16_convs'

### ISSUE THREAD

**Issue by 2017hack** [yuxng/PoseCNN#10]
Hi, when i run the ./experiment/script/demo.sh, i meet the error, "KeyError: 'unknown network: vgg16_convs'". i don't know why, can you help me, thanks!

**Comment by saurabheights** [comment]
@2017hack : How did you resolve the issue?

**Comment by im2ex** [comment]
If you have this problem: check Issue #23. @saurabheights provided the solution there.
`conda remove easydict`
`pip install easydict`

**Comment by saurabheights** [comment]
Ohhh yeah, sorry had exams, so didnt get to provide solution. @im2ex  Thanks for doing my part. :+1:
