### ISSUE TITLE
ImportError: undefined symbol: PyUnicode_AsUTF8String when use ./experiments/scripts/lov_color_2d_train.sh 0

### ISSUE THREAD

**Issue by hatimwen** [yuxng/PoseCNN#109]
When I used ./experiments/scripts/lov_color_2d_train.sh 0, it told me this error:

Traceback (most recent call last):
  File "./tools/train_net.py", line 303, in <module>
    import libsynthesizer
ImportError: /usr/local/lib/libboost_python27.so.1.67.0: undefined symbol: PyUnicode_AsUTF8String

Have anyone met this error? If so, how did you solve this?
Thanks!

**Comment by Kaju-Bubanja** [comment]
Feel free to have a look at my master thesis, especially the appendix section A.1.1.
It explains the causes of this error and how to fix it. I think the appendix might be valuable in general for trying to get to run posecnn. You can find my thesis Textureless, Symmetric, Multiple Instances 6D Pose Estimation in Cluttered Scenes Using RGB-D Data [here.](https://drive.google.com/open?id=1nBMY-eJI7ImCw1CrDkgTVm_spVN0UQDq)

**Comment by hatimwen** [comment]
@Kaju-Bubanja Thanks a lot! I will try to figure out with your help! Thanks again! 👍 、
