### ISSUE TITLE
when I execute sh make.sh I get some problem

### ISSUE THREAD

**Issue by FransicsXu** [yuxng/PoseCNN#17]
/usr/bin/ld:Can not find  -ltensorflow_framework
collect2: error: ld returned 1 exit status
hough_voting_gpu_layer
In file included from hough_voting_op.cc:25:0:
ransac.h:31:21: fatal error: nlopt.hpp: no such directory
compilation terminated.
hough_voting_layer

i install tensorflow-gpu through pip
my python version is 2.7

How can I solve this ??
thx!!!

**Comment by MyGithub55555** [comment]
you can try tensorflow 1.4.0 and the problem will be fixed.
