### ISSUE TITLE
Make error for compiling synthesize

### ISSUE THREAD

**Issue by kemangjaka** [yuxng/PoseCNN#2]
Hi Yu Xiang,

Thank you so much for providing the code of pose estimation. 
I followed your README instructions and have been a problem with installing.

At step 4, the command "make" produced the errors related to pangolin and opengl.
For example, 

```
home/PoseCNN/lib/synthesize/synthesize.cpp:748:58: error: no matching function for call to ‘df::GLRenderer<df::CanonicalVertRenderType>::setProjectionMatrix(pangolin::OpenGlMatrixSpec&)’
   renderer_->setProjectionMatrix(projectionMatrix_reverse);

/home/PoseCNN/lib/synthesize/synthesize.cpp:789:39: error: no matching function for call to ‘pangolin::OpenGlMatrix::OpenGlMatrix(Eigen::Matrix4f&)’
     pangolin::OpenGlMatrix mvMatrix(mv);

/home/PoseCNN/lib/synthesize/synthesize.cpp:1951:50: error: no matching function for call to ‘df::GLRenderer<df::CanonicalVertRenderType>::setProjectionMatrix(pangolin::OpenGlMatrixSpec&)’
   renderer_->setProjectionMatrix(projectionMatrix);
```

Do you have any ideas for solving these errors? 

Thank you!

The system information follows.
OS: Ubuntu14.04
Python:3.5

**Comment by yuxng** [comment]
Can you list all the error messages? This may be due to a wrong version of Pangolin.

**Comment by kemangjaka** [comment]
Hi, 

Thanks for the quick reply. 
There are a lots of I paste the log text file of the "make". 
[make.log](https://github.com/yuxng/PoseCNN/files/1882441/make.log)

I followed the instruction of Pangolin to install it.
https://github.com/stevenlovegrove/Pangolin

Thank you

**Comment by yuxng** [comment]
The error comes from Pangolin. Try to make sure you compile Pangolin with Eigen.

**Comment by kemangjaka** [comment]
Thx!!
I got the demo code working.

**Comment by mcimpoi** [comment]
> Can you list all the error messages? This may be due to a wrong version of Pangolin.
Could you please specify the version for Pangolin (and other dependencies) in the README?
