### ISSUE TITLE
Demo tries to use vgg16_conv, but only defines vgg16

### ISSUE THREAD

**Issue by im2ex** [yuxng/PoseCNN#23]
Hello, after a lot of version conflicts I managed to compile :-)

Running demo.sh fails with "KeyError: 'Unknown network: vgg16_conv'" though.
I can understand this since with  __C.TRAIN.SINGLE_FRAME = False in fcn/config.py 
networks/factory.py only defines vgg16.

**So from my understanding demo.sh can not work as it is checked in right now.**

A simple change from --network vgg16_conf to vgg16 does not help and fails with other errors. 
Thanks for any help towards a working demo.

**Comment by saurabheights** [comment]
Any updates on this?

**Comment by saurabheights** [comment]
@im2ex : The bug is in easydict. Check if your easydict version is 1.4 using `conda list`. If so, uninstall it, and use easydict 1.7. Also, the config file is also loaded from a file, check demo.sh, cfg param. This loaded file is not used due to bug in easydict.

`conda remove easydict`
`pip install easydict `

**Comment by im2ex** [comment]
@saurabheights: Thanks a lot!
Demo runs now.

**Comment by youkenhou** [comment]
@im2ex Could you please tell me the versions of libraries you used to compile successfully? I've met so many errors while running demo. Thank you.

**Update**: Finally I managed to get the demo working. Here is my environment:
Ubuntu 16.04
CUDA 8.0
Tensorflow 1.4.0-gpu

**Comment by im2ex** [comment]
sorry, saw too late. Good that you managed.
Did you also manage training? I still struggle with that.

**Comment by youkenhou** [comment]
@im2ex Thank you for your attention. I'm sorry but I haven't tried training because the dataset is too large for my hard disk. If I managed to train I'll update here. Wish you good luck.

**Comment by saurabheights** [comment]
@im2ex @youkenhou : FYI One important thing, both for training and running ICP as post step to pose detection, you need to compile lib/synthesize module. The cfg file i mentioned before
> Also, the config file is also loaded from a file, check demo.sh, cfg param

In the configuration file experiments/cfgs/lov_color_2d.yml, the second last param POSE_REFINE: False disables the ICP step. 

Compiling lib/synthesize is another problem I am facing. If anyone of you gets it done, please let me know the library versions, cuda, gcc, tensorflow, etc.
