### ISSUE TITLE
Demo dependencies missing - ImportError: cannot import name gpu_normals

### ISSUE THREAD

**Issue by saurabheights** [yuxng/PoseCNN#36]
I am trying to run `./experiments/scripts/demo.sh 0`

I have installed following till now:-

1. `pip install opencv-contrib-python==3.4.1.15`
2. `conda install scipy`
3. `sudo apt-get install python3-setuptools ` 
4. `pip install cython`
5. `pip install -U pip setuptools`  
6. `pip install transforms3d`

I am currently stuck with `ImportError: cannot import name gpu_normals`. Please could you suggest which library this is?

Ofcourse, would help others if you add these dependencies to readme with versions as well.

**Comment by TotoLulu94** [comment]
Did you go into
`cd $ROOT/lib`
and run 
`python setup.py build_ext --inplace`
before running the demo ? If not, it should import gpu_normals. 
see https://github.com/yuxng/PoseCNN/issues/15

**Comment by saurabheights** [comment]
Got it working. @TotoLulu94 : Thanks. This step should be added to README.md.

For users: after above commands, I have executed following
`sudo apt-get install libeigen3-dev`
`python setup.py build_ext --inplace`
`conda install -c auto easydict`

I am still facing error after this but thats due to Tensorflow and cuda9.2 conflict. But hopefully should run after this. Will update if any further issue.

**Comment by Abdul-Mukit** [comment]
I did that, but after that now I am getting this:
fatal error: Eigen/Eigen: No such file or directory

**Comment by Luedeke** [comment]
@Abdul-Mukit  Have you read the Post from saurabheights?

Fatal error: Eigen/Eigen: No such file or directory

You should be able to fix this error with the following code:

sudo apt-get install libeigen3-dev 

Perhaps this more detailed installation application will help you.
https://github.com/Kaju-Bubanja/PoseCNN/tree/docu_updated
But there is a typo: Eigen 3.3.5 ! not Eigen 3.3.9

If you want to use Eigen from source, dont forgett:
mkdir build
cd build
cmake ..
make
sudo make install

**Comment by iris0329** [comment]
> I did that, but after that now I am getting this:
> fatal error: Eigen/Eigen: No such file or directory

@Abdul-Mukit 
check if your eigen path same as the code author written in `lib/setup.py`
for me, eigen path is different in my server, so after changing the path, it works
