### ISSUE TITLE
implementation problems

### ISSUE THREAD

**Issue by doublechenchen** [yuxng/PoseCNN#4]
Hi Yu Xiang,

Thanks for providing the code for your paper. I met some problems when run the commands that you provided.

when i run the following:
    ```Shell
    cd $ROOT/lib/synthesize
    mkdir build
    cd build
    cmake ..
    make
    ```
There were some problems, it said 'can't fine the  #include <df/camera/camera.h>'
how can i find all the df files?

Thanks.

**Comment by yuxng** [comment]
These files are under lib/kinect_fusion/include

**Comment by doublechenchen** [comment]
thank you, i have found the files, but i have an error when run   ' ./experiments/scripts/demo.sh '
 it said:'tensorflow.python.framework.errors_impl.NotFoundError: /home/cc/PoseCNN/tools/../lib/average_distance_loss/average_distance_loss.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
'

**Comment by yuxng** [comment]
See #1 
The error may because the flag -D_GLIBCXX_USE_CXX11_ABI=0 in compiling the new layers.
If your tensorflow is compiled with -D_GLIBCXX_USE_CXX11_ABI=0, you need to add -D_GLIBCXX_USE_CXX11_ABI=0 to the make.sh file to compile. I think for pre-built tensorflow, you need to add this flag.

**Comment by doublechenchen** [comment]
i added it, but still with the same error.
i added :'nvcc -std=c++11 -c -o average_distance_loss_op_gpu.cu.o average_distance_loss_op_gpu.cu.cc \
	-I $TF_INC -I$TF_INC/external/nsync/public -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_50

g++ -std=c++11 -shared -o average_distance_loss.so average_distance_loss_op.cc \
	average_distance_loss_op_gpu.cu.o -I $TF_INC -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -I$TF_INC/external/nsync/public -fPIC -lcudart -L$CUDA_PATH/lib64 -L$TF_LIB -ltensorflow_framework '
should i add like this?

**Comment by cneeruko** [comment]
did you solve this ? @doublechenchen

**Comment by cneeruko** [comment]
@yuxng  I get Segmentation fault while running the demo.
I see there is no data flow from hough voting layer i.r. the roi tensor does not return any value when being evaluated. I wonder if this is because the hough_voting_layer is not compiled properly. Is this the proper way?


nvcc -std=c++11 -c -o hough_voting_gpu_op.cu.o hough_voting_gpu_op.cu.cc \
	-I $TF_INC -D_GLIBCXX_USE_CXX11_ABI=0 -I$TF_INC/external/nsync/public -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_50

g++ -std=c++11 -shared -o hough_voting_gpu.so hough_voting_gpu_op.cc \
	hough_voting_gpu_op.cu.o -I $TF_INC -D_GLIBCXX_USE_CXX11_ABI=0 -I$TF_INC/external/nsync/public -fPIC -lcudart -lcublas -lopencv_imgproc -lopencv_calib3d -lopencv_core -L $CUDA_PATH/lib64 -L$TF_LIB -ltensorflow_framework

**Comment by rajatvikramsingh** [comment]
Adding "-D_GLIBCXX_USE_CXX11_ABI=0" to the nvcc commands too gets rid of this error.

**Comment by iris0329** [comment]
> @yuxng I get Segmentation fault while running the demo.
> I see there is no data flow from hough voting layer i.r. the roi tensor does not return any value when being evaluated. I wonder if this is because the hough_voting_layer is not compiled properly. Is this the proper way?
> 
> nvcc -std=c++11 -c -o hough_voting_gpu_op.cu.o hough_voting_gpu_op.cu.cc 
> -I $TF_INC -D_GLIBCXX_USE_CXX11_ABI=0 -I$TF_INC/external/nsync/public -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_50
> 
> g++ -std=c++11 -shared -o hough_voting_gpu.so hough_voting_gpu_op.cc 
> hough_voting_gpu_op.cu.o -I $TF_INC -D_GLIBCXX_USE_CXX11_ABI=0 -I$TF_INC/external/nsync/public -fPIC -lcudart -lcublas -lopencv_imgproc -lopencv_calib3d -lopencv_core -L $CUDA_PATH/lib64 -L$TF_LIB -ltensorflow_framework

@cneeruko do u solve this problem? thank u

**Comment by Nathan-81** [comment]
I'm having a similar error but the solution given above changed anything.
here is my error : tensorflow.python.framework.errors_impl.NotFoundError: /home/wongch79/Programming/6dposeest-posecnn/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZTVN10tensorflow14kernel_factory17OpKernelRegistrar18PtrOpKernelFactoryE

PS : I built tensorflow from source with the flag : -D_GLIBCXX_USE_CXX11_ABI=0

**Comment by XuanAo1016** [comment]
> I'm having a similar error but the solution given above changed anything.
> here is my error : tensorflow.python.framework.errors_impl.NotFoundError: /home/wongch79/Programming/6dposeest-posecnn/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZTVN10tensorflow14kernel_factory17OpKernelRegistrar18PtrOpKernelFactoryE
> 
> PS : I built tensorflow from source with the flag : -D_GLIBCXX_USE_CXX11_ABI=0

Hi, Nathan-81, have you solve this issue with error "_ZTVN10tensorflow14kernel_factory17OpKernelRegistrar18PtrOpKernelFactoryE" ?
