### ISSUE TITLE
KeyError: 'Unknown network: vgg16_convs'

### ISSUE THREAD

**Issue by nkalavak** [yuxng/PoseCNN#41]
I get the following error when I run `./experiments/scripts/lov_color_2d_train.sh 0`

```
Traceback (most recent call last):
  File "./tools/train_net.py", line 328, in <module>
    network = get_network(args.network_name)
  File "/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/networks/factory.py", line 50, in get_network
    raise KeyError('Unknown network: {}'.format(name))
KeyError: 'Unknown network: vgg16_convs'
```
I am not sure what is causing this considering the vgg16_convs file exists and is one of the imported networks.

**Comment by im2ex** [comment]
check closed issue #23. 
Most likely wrong version of easydict

**Comment by nkalavak** [comment]
I am using easydict 1.7. I uninstalled and reinstalled, just in case. It does not fix the error.
Plus, I am able to successfully run the demo. The issue arises while trying to train.

**Comment by im2ex** [comment]
ah ok. 
I didn't manage to train yet either (other problem though)

**Comment by yuxng** [comment]
I do not know what is wrong here. This did not happen to me.

**Comment by Santranx** [comment]
@nkalavak hello, would you tell me what did you do to fix the problem?
