### ISSUE TITLE
how to understand the result of demo?

### ISSUE THREAD

**Issue by Santranx** [yuxng/PoseCNN#43]
how to understand the result of demo? when I run the demo.sh, I get the result as follows. what's the meaning of the 3*4 matrix? Is there any other graph result？

``data/demo_images/000001-color.png
[0, 4, 2, 3, 1]
[[   0.     2.   283.5  133.2  514.5  392.8 1870. ]
 [   0.    15.    38.4  233.8  337.6  370.2 1217. ]
 [   0.     5.   317.8  240.3  410.2  431.7 1192. ]
 [   0.    10.    95.6  306.8  280.4  487.2  844. ]
 [   0.     4.   372.4  250.9  473.6  363.1  630. ]]
im_segment: 0/5 2.584s 0.000s
/home/l00404262/pose-cnn/posecnn/output/images/vgg16_fcn_color_single_frame_2d_pose_add_lov_iter_160000/mat/000000.mat
003_cracker_box
[[ 0.6422991   0.11825264  0.75727683  0.08245494]
 [ 0.2812132   0.8827622  -0.37636426  0.02077807]
 [-0.71300143  0.45469466  0.53374314  1.022648  ]]

035_power_drill
[[-0.36496866  0.9297555  -0.04850226 -0.11761715]
 [-0.22443092 -0.03730001  0.9737758   0.05707268]
 [ 0.90356433  0.36628312  0.22227931  1.0038762 ]]

006_mustard_bottle
[[-0.27254885 -0.9612891   0.04050098  0.04041607]
 [-0.52675986  0.11385927 -0.8423539   0.07496937]
 [ 0.80513424 -0.2509169  -0.5374007   0.8451747 ]]

011_banana
[[ 0.7152798  -0.65476066 -0.24426067 -0.09588137]
 [-0.47088557 -0.19330123 -0.86075634  0.11935466]
 [ 0.5163735   0.73070043 -0.4465818   0.8183588 ]]

005_tomato_soup_can
[[-0.24271648 -0.96719044  0.07504287  0.09861922]
 [-0.48978522  0.05540327 -0.870081    0.05884667]
 [ 0.8373764  -0.24793784 -0.48716292  0.9562935 ]]

data/demo_images/000005-color.png
[3, 1, 2, 0, 4]
[[   0.    15.   222.9  108.7  445.1  335.3 1785. ]
 [   0.     3.   188.6  304.3  373.4  451.7 1764. ]
 [   0.    12.   102.7   98.2  241.3  291.8 1745. ]
 [   0.     2.    87.8   26.   312.2  290.  1697. ]
 [   0.    19.   341.7  244.6  502.3  407.4  927. ]]
im_segment: 4/5 0.256s 0.000s
/home/l00404262/pose-cnn/posecnn/output/images/vgg16_fcn_color_single_frame_2d_pose_add_lov_iter_160000/mat/000004.mat
035_power_drill
[[-0.79307353  0.03152163  0.6083097   0.01757701]
 [-0.2863282  -0.9007414  -0.3266206  -0.01614243]
 [ 0.53763413 -0.4332104   0.7233798   0.89233726]]

004_sugar_box
[[-0.05908491 -0.15062854  0.9868232  -0.0249941 ]
 [-0.88968515  0.45628068  0.01637772  0.10673593]
 [-0.4527353  -0.8769943  -0.16097128  0.83356476]]

021_bleach_cleanser
[[-0.9080525  -0.4185388  -0.01629667 -0.12675728]
 [-0.2248048   0.5198222  -0.8241648  -0.04160914]
 [ 0.35341638 -0.7447215  -0.5661153   0.95910937]]

003_cracker_box
[[-0.27735838  0.9571752   0.08299295 -0.10655584]
 [ 0.50783616  0.21938507 -0.83305013 -0.07851676]
 [-0.8155824  -0.18890665 -0.54693645  1.0060583 ]]

051_large_clamp
[[ 0.98945546 -0.14415832 -0.01401017  0.09840345]
 [-0.09128212 -0.54556674 -0.8330814   0.076396  ]
 [ 0.11245212  0.8255758  -0.5529731   0.9629544 ]]

data/demo_images/000004-color.png
[2, 0, 1]
[[   0.    11.   221.    75.9  463.   342.1 3526. ]
 [   0.     5.   332.8  249.9  447.2  428.1 1270. ]
 [   0.     6.   213.8  303.3  328.2  428.7  814. ]]
im_segment: 3/5 0.221s 0.000s
/home/l00404262/pose-cnn/posecnn/output/images/vgg16_fcn_color_single_frame_2d_pose_add_lov_iter_160000/mat/000003.mat
019_pitcher_base
[[ 0.57848835  0.8078584   0.11276557  0.02698041]
 [ 0.57146865 -0.30274802 -0.7627366  -0.03002721]
 [-0.58204365  0.5056762  -0.63680196  0.9920388 ]]

006_mustard_bottle
[[ 0.68264264  0.71917355  0.12957029  0.06465604]
 [ 0.52466255 -0.3589347  -0.77194256  0.08196001]
 [-0.50865334  0.5949416  -0.6223476   0.8956092 ]]

007_tuna_fish_can
[[-0.4215358  -0.5414055   0.7274529  -0.0353383 ]
 [-0.90422386  0.31152016 -0.29212058  0.10487492]
 [-0.06846057 -0.7809195  -0.6208687   0.8978541 ]]

data/demo_images/000002-color.png
[1, 3, 0, 2, 4]
[[0.000e+00 3.000e+00 1.825e+02 2.725e+02 3.475e+02 4.375e+02 1.573e+03]
 [0.000e+00 1.200e+01 2.132e+02 8.910e+01 3.188e+02 2.629e+02 1.375e+03]
 [0.000e+00 1.000e+00 2.912e+02 1.539e+02 4.188e+02 3.101e+02 1.304e+03]
 [0.000e+00 4.000e+00 3.704e+02 2.414e+02 4.936e+02 3.646e+02 8.610e+02]
 [0.000e+00 1.700e+01 6.320e+01 3.210e+02 2.128e+02 3.870e+02 4.470e+02]]
im_segment: 1/5 0.225s 0.000s
/home/l00404262/pose-cnn/posecnn/output/images/vgg16_fcn_color_single_frame_2d_pose_add_lov_iter_160000/mat/000001.mat
004_sugar_box
[[-0.15976454  0.9531169  -0.25698918 -0.04170658]
 [-0.77241707 -0.2828072  -0.5686756   0.09874432]
 [-0.6146927   0.10764863  0.7813864   0.9271626 ]]

021_bleach_cleanser
[[ 0.889594   -0.4554014  -0.0351006  -0.04652733]
 [-0.19150709 -0.30211905 -0.93383586 -0.06462913]
 [ 0.41466552  0.8374568  -0.3559759   1.0563438 ]]

002_master_chef_can
[[ 0.73876274 -0.6727802   0.03995484  0.0403282 ]
 [-0.30980563 -0.39164263 -0.8663928  -0.00893156]
 [ 0.59854     0.6276805  -0.49776208  1.0239959 ]]

005_tomato_soup_can
[[-0.4866409  -0.3669129  -0.792815    0.09678001]
 [ 0.76156765 -0.62281054 -0.1792256   0.05013151]
 [-0.42801332 -0.69100076  0.582514    0.86749095]]

037_scissors
[[ 0.21864083  0.9612652  -0.16782571 -0.14670825]
 [ 0.4488678   0.05363503  0.89198714  0.09441528]
 [ 0.8664375  -0.2703564  -0.4197542   0.89438194]]

data/demo_images/000003-color.png
[2, 1, 0]
[[   0.    13.   298.5  244.1  551.5  483.9 2656. ]
 [   0.     9.   136.8  211.6  295.2  374.4 1019. ]
 [   0.     4.   174.   302.8  284.   439.2  971. ]]
im_segment: 2/5 0.230s 0.000s
/home/l00404262/pose-cnn/posecnn/output/images/vgg16_fcn_color_single_frame_2d_pose_add_lov_iter_160000/mat/000002.mat
024_bowl
[[ 0.94938517  0.29547584  0.10659184  0.08527517]
 [ 0.22814123 -0.41536832 -0.8805798   0.09334073]
 [-0.21591519  0.8603274  -0.46175474  0.81213427]]

010_potted_meat_can
[[-0.96951807  0.24496381  0.00523676 -0.08112083]
 [ 0.15087484  0.61370015 -0.7749896   0.04320456]
 [-0.19305821 -0.7505764  -0.6319522   0.8922638 ]]

005_tomato_soup_can
[[-0.1556726  -0.98779947 -0.00426031 -0.06283883]
 [-0.71000516  0.11489002 -0.69476104  0.09696867]
 [ 0.6867741  -0.10513044 -0.7192279   0.7981611 ]]

42.40user 6.38system 0:12.40elapsed 393%CPU (0avgtext+0avgdata 3729156maxresident)k
0inputs+64outputs (0major+956187minor)pagefaults 0swaps

**Comment by Santranx** [comment]
the matrix is [R T] matrix. the R is 3*3, the T is 3*1. The unit of values in T is meter.

**Comment by mrlooi** [comment]
I guess I can provide a more intuitive layman's answer:
The matrix is a 3x4 matrix. 
- The first 3 columns forms the 3x3 rotation matrix R. 
- The last column is the translation T, which represents the distance between the center of the object and the camera in x y z respectively. z is the depth value (always positive), while x and y are all relative to the center of the image (could be negative or positive). 

As a simple example, let's take the matrix 
[[-0.1556726 -0.98779947 -0.00426031 -0.06283883]
[-0.71000516 0.11489002 -0.69476104 0.09696867]
[ 0.6867741 -0.10513044 -0.7192279 0.7981611 ]]

T is [-0.06283883,0.09696867,0.7981611]. x-value of -0.063 means that the object centroid is 0.063m to the left of the image center, while y-value of 0.097 means that the object centroid is 0.097m below the image center.
