### ISSUE TITLE
queastion about implementation

### ISSUE THREAD

**Issue by doublechenchen** [yuxng/PoseCNN#5]
it this the right way to add the -D_GLIBCXX_USE_CXX11_ABI=0 ?

nvcc -std=c++11 -c -o average_distance_loss_op_gpu.cu.o average_distance_loss_op_gpu.cu.cc \
	-I $TF_INC -D_GLIBCXX_USE_CXX11_ABI=0 -I$TF_INC/external/nsync/public -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_50

g++ -std=c++11 -shared -o average_distance_loss.so average_distance_loss_op.cc \
	average_distance_loss_op_gpu.cu.o -I $TF_INC -D_GLIBCXX_USE_CXX11_ABI=0 -I$TF_INC/external/nsync/public -fPIC -lcudart -L$CUDA_PATH/lib64 -L$TF_LIB -ltensorflow_framework

**Comment by yuxng** [comment]
Add -D_GLIBCXX_USE_CXX11_ABI=0 after "-ltensorflow_framework"
