### ISSUE TITLE
What densities should the pointclouds of the models have?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [yuxng/PoseCNN#53]
If I have a cad model and can export it to a pointcloud with different densities how did you determine what density to export the model in? I guess just more points is not necessarily better, but a density closest  to what the sensor is going to return, which brings me to another question. Did you use different densities and make a pyramid or how else did you handle that the objects might be sometimes far away and sometimes close, making icp not work in all cases?

**Comment by yuxng** [comment]
In ICP, I project the 3D model to the image using the pose estimation into a depth image, and then extract the point cloud from the depth image. So the density relates to how far the object is from the camera.

**Comment by Kaju-Bubanja** [comment]
I don't understand completely. When I look at data/LOV/models/004_sugar_box I see points.xyz which represent the model of the sugar box. But how did you obtain these? I assume you had a cad model and exported a mesh of it somehow, but for this you would need to know the point density in which to export? So my main question is how did you get your models and the corresponding mesh/points.xyz?

**Comment by yuxng** [comment]
I just uniformly sampled 3000 points and saved the points.xyz file. You can do more sophisticated sampling for sure.
