### ISSUE TITLE
How to create a dataset?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [yuxng/PoseCNN#57]
I was wondering whether this repo contains code that helps with the generation of a dataset? Can you or do you plan on open sourcing the code used to create a dataset? Or is it already in the package and I just didn't find it?

**Comment by Abdul-Mukit** [comment]
Hi, @Kaju-Bubanja. How make the dataset? I studied the article several times but didn't understand the 6D pose annotation part. 
The paragraph goes like this:
"_To avoid annotating all the video frames manually, we manually specify the poses of the objects only in the first frame of each video. Using Signed Distance Function (SDF) representations of each object, we refine the pose of each object in the first depth frame. Next, the camera trajectory is initialized by fixing the object poses relative to one another and tracking the object configuration through the depth video. Finally, the camera trajectory and relative object poses are refined in a global optimization step._"

How were the 6D poses determined in the first frame? I don't get it. Also, I don't see any marker field for camera pose detection. Moreover the objects seem to be on top of each other in many frames and not on the base as in LINEMOD dataset.

If you fond the codes for pose annotation can you please mention which codes are these?

**Comment by Kaju-Bubanja** [comment]
There is no Code in the Repo to produce a Dataset. I wrote my own and used a vicon system and blender to generate a dataset. I will be able to tell you how exactly to do that in the future, but not right now.

**Comment by RobbyHuang** [comment]
Hi， @Kaju-Bubanja @Abdul-Mukit ，I want to creat a new datasets ,and I met the same problem that how to annotating the poses of the objects in the first frame of each video. 
Do you know how to get ground-truth annotations for object poses?

**Comment by Abdul-Mukit** [comment]
I moved on to DOPE and NDDS both from Nvidia research. NDDS  is great for synthetic data generation.

**Comment by Kaju-Bubanja** [comment]
Feel free to have a look at my master thesis, especially the section 3.4 Dataset generation.
You can find my thesis Textureless, Symmetric, Multiple Instances 6D Pose Estimation in Cluttered Scenes Using RGB-D Data [here](https://drive.google.com/file/d/1nBMY-eJI7ImCw1CrDkgTVm_spVN0UQDq/view).

**Comment by RobbyHuang** [comment]
@Kaju-Bubanja thanks for your share
@Abdul-Mukit  thanks your advice
I finally choose labelfusion and NDDS

THANKS

**Comment by pra-dan** [comment]
@Abdul-Mukit What was your last choice for 6D pose estimation ? PoseCNN or DOPE ? I am planning to train it for a single custon object

**Comment by Abdul-Mukit** [comment]
@pra-dan DOPE. I got the job done quickly with it. I am sure there are better and faster pose estimators out there now. I have been busy with other stuff. Can you let me know which estimator you end up working with later?
