### ISSUE TITLE
make error pangolin::GlBuffer::GlBuffer

### ISSUE THREAD

**Issue by atabakd** [yuxng/PoseCNN#75]
I'm getting this strange error that once just gracefully disappeared!

`In file included from /usr/include/c++/5/vector:62:0,
                 from /media/Extra/dsl/pose2/PoseCNN/lib/synthesize/synthesize.hpp:6,
                 from /media/Extra/dsl/pose2/PoseCNN/lib/synthesize/synthesize.cpp:1:
/usr/include/c++/5/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = pangolin::GlBuffer; _Args = {const pangolin::GlBuffer&}]’:
/usr/include/c++/5/bits/stl_uninitialized.h:75:18:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const pangolin::GlBuffer*, std::vector<pangolin::GlBuffer> >; _ForwardIterator = pangolin::GlBuffer*; bool _TrivialValueTypes = false]’
/usr/include/c++/5/bits/stl_uninitialized.h:126:15:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const pangolin::GlBuffer*, std::vector<pangolin::GlBuffer> >; _ForwardIterator = pangolin::GlBuffer*]’
/usr/include/c++/5/bits/stl_uninitialized.h:281:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const pangolin::GlBuffer*, std::vector<pangolin::GlBuffer> >; _ForwardIterator = pangolin::GlBuffer*; _Tp = pangolin::GlBuffer]’
/usr/include/c++/5/bits/stl_vector.h:322:31:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = pangolin::GlBuffer; _Alloc = std::allocator<pangolin::GlBuffer>]’
/media/Extra/dsl/pose2/PoseCNN/lib/synthesize/synthesize.hpp:105:7:   required from ‘boost::python::objects::value_holder<Value>::value_holder(PyObject*, A0) [with A0 = boost::reference_wrapper<const Synthesizer>; Value = Synthesizer; PyObject = _object]’
/usr/local/include/boost/python/object/make_instance.hpp:72:48:   [ skipping 6 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/local/include/boost/python/object/class_metadata.hpp:227:55:   required from ‘static void boost::python::objects::class_metadata<T, X1, X2, X3>::register_aux2(T2*, Callback) [with T2 = Synthesizer; Callback = boost::integral_constant<bool, false>; T = Synthesizer; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]’
/usr/local/include/boost/python/object/class_metadata.hpp:218:38:   required from ‘static void boost::python::objects::class_metadata<T, X1, X2, X3>::register_aux(void*) [with T = Synthesizer; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]’
/usr/local/include/boost/python/object/class_metadata.hpp:204:37:   required from ‘static void boost::python::objects::class_metadata<T, X1, X2, X3>::register_() [with T = Synthesizer; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]’
/usr/local/include/boost/python/class.hpp:450:28:   required from ‘void boost::python::class_<T, X1, X2, X3>::initialize(const DefVisitor&) [with DefVisitor = boost::python::init_base<boost::python::init<std::basic_string<char>, std::basic_string<char> > >; W = Synthesizer; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]’
/usr/local/include/boost/python/class.hpp:204:9:   required from ‘boost::python::class_<T, X1, X2, X3>::class_(const char*, const boost::python::init_base<DerivedT>&) [with DerivedT = boost::python::init<std::basic_string<char>, std::basic_string<char> >; W = Synthesizer; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]’
/media/Extra/dsl/pose2/PoseCNN/lib/synthesize/synthesize.hpp:250:70:   required from here
/usr/include/c++/5/bits/stl_construct.h:75:7: error: use of deleted function ‘pangolin::GlBuffer::GlBuffer(const pangolin::GlBuffer&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
In file included from /usr/local/include/pangolin/pangolin.h:33:0,
                 from /media/Extra/dsl/pose2/PoseCNN/lib/synthesize/synthesize.hpp:15,
                 from /media/Extra/dsl/pose2/PoseCNN/lib/synthesize/synthesize.cpp:1:
/usr/local/include/pangolin/gl/gl.h:223:5: note: declared here
     GlBuffer(const GlBuffer&) = delete;
     ^
CMakeFiles/synthesizer.dir/build.make:62: recipe for target 'CMakeFiles/synthesizer.dir/synthesize.cpp.o' failed
make[2]: *** [CMakeFiles/synthesizer.dir/synthesize.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/synthesizer.dir/all' failed
make[1]: *** [CMakeFiles/synthesizer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
I don't understand the issue with` /usr/include/c++/5/bits/stl_construct.h:75:7: error: use of deleted function ‘pangolin::GlBuffer::GlBuffer(const pangolin::GlBuffer&)’`. Any help is appreciated.

**Comment by Abdul-Mukit** [comment]
I am getting the same error:
error: use of deleted function ‘pangolin::GlBuffer::GlBuffer(const pangolin::GlBuffer&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }

@atabakd did you find any solution? 

I am thinking whether it has anything to do with the installation of pangolin. I just downloaded the latest from pangolin's github repo and installed from source. didn't check out the suggested commit.

**Comment by Abdul-Mukit** [comment]
I reinstalled Pangolin but this time I used the commit c2a6ef524401945b493f14f8b5b8aa76cc7d71a9.
That solved my problem. Hope this helps.

**Comment by atabakd** [comment]
In my case, the issue was with `make -j1`, which according to @Kaju-Bubanja, I shouldn't have done.
Anyhow, if you only need the demo, I made a docker [here](https://github.com/atabakd/PoseCNNDocker).
