### ISSUE TITLE
Cannot find the includes with 'df/*' while compiling synthesize lib

### ISSUE THREAD

**Issue by krips89** [yuxng/PoseCNN#8]
I get the following error while trying to compile the synthesis lib.

    df/camera/camera.h: No such file or directory

I indeed see some hard-coded paths in the CMakeLists.txt. For example: 

    set(xFusion_ROOT "/home/yuxiang/Projects/Deep_Pose/lib/kinect_fusion")

Which could be reason.

**Comment by haudren** [comment]
This was fixed in my [fork](https://github.com/haudren/PoseCNN)

**Comment by krips89** [comment]
Why was this closed? This was not fixed in this branch. Still I see hard coded paths.

**Comment by Cheren15** [comment]
I have the same problem...

**Comment by krips89** [comment]
@haudren Hello, I can't open issue in your forked repo. 
Wanted to ask, how can I rebuild the layers (in the lib folder). There is no make.sh.

**Comment by haudren** [comment]
@krips89 : No need to use make.sh, the `setup.py` takes care of building all the custom layers.
