### ISSUE TITLE
implementation problem

### ISSUE THREAD

**Issue by 2017hack** [yuxng/PoseCNN#9]
hi, i have two questions for asking 
1, when i do ./experiments/scripts/demo.sh,  i just run this script and it happens an error like below
"AssertionError: Data path does not exist: ../../data/LOV/data". i hope to know whether i need to download the YCB-Video dataset when run this demo.sh.
2, The size of the YCB-Video dataset is two large, about 256G, and not easy to save on disk. can you give a small one, or separate the dataset to a small set. 
    Appreciate your reply!

**Comment by cneeruko** [comment]
I have the above two issues.
Any ideas on how it was solved ?

Best,
